Bump sphinx to v3.1.2 and fix docs
pypa/pypa.io pull request #60
Opened 2020-07-30 04:51 UTC by shireenrao

This is to update Sphinx to v3.1.2 along with fixing the following 

- pypug reference in conf.py
- Fix all the references and links which were causing warnings and rendering issues.

This PR was made based on discussions at https://github.com/pypa/pip/issues/8650#issuecomment-665858951

2020-07-31 12:32 UTC, shireenrao commented
@brainwane - can you please review this PR?

2020-11-01 20:00 UTC, webknjaz requested changes
Overall, many places are relevant but I've spotted a few typos that need to be corrected. See the inline comments for details.

2020-11-01 20:00 UTC, webknjaz commented on source/specifications.rst
> +the `Python language reference <https://docs.python.org/dev/reference/>`
This syntax is invalid too: links should have a trailing underscore.
```suggestion
the `Python language reference <https://docs.python.org/dev/reference/>`_
```

2020-11-12 12:51 UTC, shireenrao commented on requirements.txt
> +maksphinx==3.1.2
Yup.. That was a typo. Thank you for catching that.

2020-11-12 13:25 UTC, shireenrao reviewed
Accepting all the changes

2020-12-29 15:14 UTC, merged

2020-12-29 15:14 UTC, brainwane commented
Thanks, and sorry for the delay!